name: Secrets and env value call

on:
  pull_request: 
    branches:
      - main

env:
  qa_url: "https://qa.example.com"

jobs:
  env:
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: Print repository secret
        run: echo "Repository API Key is ${{ secrets.API_KEY }}"

      - name: Print environment secret
        run: echo "QA API Key is ${{ secrets.QA_API_KEY }}"

      - name: Print environment variable
        run: echo "QA URL is ${{ env.qa_url }}"
